apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-todo-list
  namespace: nstodolist
  labels:
    app: react-todo-list
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-todo-list
  strategy:
    type: RollingUpdate  # Update strategy
    rollingUpdate:
      maxSurge: 1  # MaxPods adicionales cuando updeteamos
      maxUnavailable: 0  
  template:
    metadata:
      labels:
        app: react-todo-list
    spec:
      containers:
      - name: website
        image: edgar4all/react-todo-list:3
        ports:
        - containerPort: 3000